export default {

  PRODUCTS_RECEIVED: 'PRODUCTS_RECEIVED',
  PRODUCT_SELECTED: 'PRODUCT_SELECTED',
  NEW_BOOKING_RECEIVED: 'NEW_BOOKING_RECEIVED',
  BOOKINGS_RECEIVED:'BOOKINGS_RECEIVED',
  CURRENT_USER_RECEIVED:'CURRENT_USER_RECEIVED',
  USER_LOGGED_OUT:'USER_LOGGED_OUT',
  ADD_FLASH_MESSAGE:'ADD_FLASH_MESSAGE'

}
